#cmake file to set compiler flags for some of the known compilers
if (${CMAKE_Fortran_COMPILER_ID} MATCHES "Intel")
	message("Intel Fortran detected")
	message("THESE FLAGS ARE NOT TESTED")
	if (DEFINED CMAKE_Fortran_COMPILER_VERSION_man)
		message(WARNING "awful manual compiler version set")
		set(CMAKE_Fortran_COMPILER_VERSION "${CMAKE_Fortran_COMPILER_VERSION_man}")
	endif()
	if (${CMAKE_Fortran_COMPILER_VERSION} VERSION_LESS "14.1.0.0")
		set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -mkl=parallel -openmp")
	else()
		#set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -mkl=parallel -qopenmp")
		set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -mkl=parallel ")
	endif()     
	if (${CMAKE_Fortran_COMPILER_VERSION} VERSION_GREATER "18.0.0.0")
		set(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} ")
	endif()
	set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -fpp")
	set(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -O3")
	if(${COMPOP} STREQUAL "debug")
		set(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG} -O0")
		set(COMPADD_only_own -ftrapuv -fp-stack-check -auto -fpe0 -check bounds -heap-arrays -g -traceback -warn -gen-interfaces -init=snan,arrays)
	elseif(${COMPOP} STREQUAL "check")
		set(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG} -O0")
		set(COMPADD_only_own -fpe0 -heap-arrays -C -traceback -warn -gen-interfaces -init=snan,arrays -g)
	else()
		message("unexpected COMPOP : ${COMPOP}")
	endif()
elseif(${CMAKE_Fortran_COMPILER_ID} MATCHES "XL")
   message("IBM/BG Fortran detected")
   set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -qsmp=omp -qnosave") 
   set(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -O5 -qarch=qp -qtune=qp -qsmp=omp -qnosave")
   if(${COMPOP} STREQUAL "simpl")
   	set(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG} -O0")
   elseif(${COMPOP} STREQUAL "debug")
   	set(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG} -O0")
   	set(COMPADD_only_own -qfullpath -g -qdebug=except)
   else()
   	message("unexpected COMPOP : ${COMPOP}")
   endif()
elseif(${CMAKE_Fortran_COMPILER_ID} MATCHES "GNU")
   message("gfortran detected")
   set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -ffree-form -fimplicit-none -ffree-line-length-none -x f95-cpp-input")
   set(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -O4")
	if(${COMPOP} STREQUAL "check")
		set(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG} -O0 -g -fcheck=all -Wall -fbacktrace -ffree-form -finit-real=snan  -ffpe-trap=invalid,overflow,zero,underflow,denormal")
	elseif(${COMPOP} STREQUAL "debug")
		set(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG}  -Og -g  -pg -lprofiler -fcheck=all -Wall -fbacktrace -ffpe-trap=invalid,overflow,zero,underflow,denormal ")
		SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -pg")
        SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -pg")
		set(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG}  -Og -g  -pg -lprofiler -fcheck=all -Wall -fbacktrace -ffpe-trap=invalid,overflow,zero,underflow,denormal ")
#		set(COMPADD_only_own -g -Wall  -Wno-tabs  -Wextra -fimplicit-none -fcheck=all -fbacktrace)
	else()
		message("unexpected COMPOP : ${COMPOP}")
	endif()
elseif(${CMAKE_Fortran_COMPILER_ID} MATCHES "PGI")
  message("PGI Fortran detected")
  message(FATAL_ERROR "I have no clue about this compiler, someone should set appropriate flags")
  # set(CMAKE_SHARED_LIBRARY_LINK_Fortran_FLAGS "") #fix problem in cmake
  # set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -mp -Mr8 -Mr8intrinsics  -Mcuda:kepler+ -ta:tesla:cuda7.5 -DUSE_STREAMS -DNUM_STREAMS=${N_STREAMS} -Minfo=accel -acc")
  # set(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -fast -O3")
  # set(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG} -C -traceback -O0 -g -Mchkstk -Mchkptr")
endif()
set(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} ${compadd} ${com_rel_add}")
set(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG} ${compadd} ${com_deb_add}")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${compadd} ${com_rel_add}")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${compadd} ${com_deb_add}")


if(${CMAKE_CXX_COMPILER_ID} MATCHES "GNU")
   message("g++ detected")
   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp")   #add here general lines
   set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3")
	if(${COMPOP} STREQUAL "check")
		set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -O0 -g -Wall")
	elseif(${COMPOP} STREQUAL "debug")
		set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG}  -O0 -g3 -pg -Wall")
    endif()
endif()
