#cmake file to set compiler flags for some of the known compilers
if (${CMAKE_Fortran_COMPILER_ID} MATCHES "Intel")
	message("Intel Fortran detected")
	message("THESE FLAGS ARE NOT TESTED")
	if (DEFINED CMAKE_Fortran_COMPILER_VERSION_man)
		message(WARNING "awful manual compiler version set")
		set(CMAKE_Fortran_COMPILER_VERSION "${CMAKE_Fortran_COMPILER_VERSION_man}")
	endif()
	if (${CMAKE_Fortran_COMPILER_VERSION} VERSION_LESS "14.1.0.0")
		set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -mkl=parallel -openmp")
	else()
		#set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -mkl=parallel -qopenmp")
		set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -mkl=parallel ")
	endif()     
	if (${CMAKE_Fortran_COMPILER_VERSION} VERSION_GREATER "18.0.0.0")
		set(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} ")
	endif()
	set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -fpp")
	set(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} -O3")
	if(${COMPOP} STREQUAL "debug")
		set(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG} -O0")
		set(COMPADD_only_own -ftrapuv -fp-stack-check -auto -fpe0 -check bounds -heap-arrays -g -traceback -warn -gen-interfaces -init=snan,arrays)
	elseif(${COMPOP} STREQUAL "check")
		set(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG} -O0")
		set(COMPADD_only_own -fpe0 -heap-arrays -C -traceback -warn -gen-interfaces -init=snan,arrays -g)
	else()
		message("unexpected COMPOP : ${COMPOP}")
	endif()
elseif(${CMAKE_Fortran_COMPILER_ID} MATCHES "GNU")
   message("gfortran detected")
   set(CMAKE_Fortran_FLAGS "${CMAKE_Fortran_FLAGS} -ffree-form -fimplicit-none -ffree-line-length-none -x f95-cpp-input")
   set(CMAKE_Fortran_FLAGS_RELEASE "-O3 ${CMAKE_Fortran_FLAGS_RELEASE}")
	if(${COMPOP} STREQUAL "check")
		set(CMAKE_Fortran_FLAGS_DEBUG "-O0 -g -fcheck=all -Wall -fbacktrace -ffree-form -finit-real=snan  -ffpe-trap=invalid,overflow,zero,underflow,denormal ${CMAKE_Fortran_FLAGS_DEBUG}")
	elseif(${COMPOP} STREQUAL "debug")
		SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -pg")
        SET(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -pg")
		set(CMAKE_Fortran_FLAGS_DEBUG "-Og -g  -pg -lprofiler -fcheck=all -Wall -fbacktrace -ffpe-trap=invalid,overflow,zero,underflow,denormal ${CMAKE_Fortran_FLAGS_DEBUG}")
	elseif(${COMPOP} STREQUAL "release")
	else()
		message("unexpected COMPOP : ${COMPOP}")
	endif()
else()
  message(WARNING "\n\n\n Fortran compiler detected without default flags, make sure resonable flags are added manually\n\n\n")
endif()
set(CMAKE_Fortran_FLAGS_RELEASE "${CMAKE_Fortran_FLAGS_RELEASE} ${compadd} ${com_rel_add}")
set(CMAKE_Fortran_FLAGS_DEBUG "${CMAKE_Fortran_FLAGS_DEBUG} ${compadd} ${com_deb_add}")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${compadd} ${com_rel_add}")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${compadd} ${com_deb_add}")


if(${CMAKE_CXX_COMPILER_ID} MATCHES "GNU")
   message("g++ detected")
   set(CMAKE_CXX_FLAGS "-fopenmp ${CMAKE_CXX_FLAGS}")   #add here general lines
   set(CMAKE_CXX_FLAGS_RELEASE "-O3 ${CMAKE_CXX_FLAGS_RELEASE}")
	if(${COMPOP} STREQUAL "check")
		set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g -Wall ${CMAKE_CXX_FLAGS_DEBUG}")
	elseif(${COMPOP} STREQUAL "debug")
		set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g3 -pg -Wall ${CMAKE_CXX_FLAGS_DEBUG}")
    endif()
else()
  message(WARNING "C++ compiler detected without default flags, make sure resonable flags are added manually")
endif()
