#check for CUDA and set parameters if used
message("\n\n Search for CUDA using environment CUDA_PATH")
if(( USE_CUDA OR NOT DEFINED USE_CUDA) AND DEFINED ENV{CUDA_PATH})
    message("FOUND CUDA and compiling with it.\n\n" )
    set(USE_CUDA TRUE)
    enable_language (CUDA)
    add_compile_definitions(CPP_CUDA)
    set(CUDA_PATH $ENV{CUDA_PATH})
    link_directories( ${CUDA_PATH}/lib64 )
    include_directories( ${CUDA_PATH}/include )
    if(NOT DEFINED CMAKE_CUDA_ARCHITECTURES)
        set(CMAKE_CUDA_ARCHITECTURES 75)
    endif()
elseif(USE_CUDA AND NOT DEFINED ENV{CUDA_PATH})
    message( FATAL_ERROR "Enforcing to use cuda, but CUDA_PATH is not defined.\n Export the CUDA_PATH environment variable or remove USE_CUDA in config.cmake\n\n" )
else()
    message( "Skipping CUDA-part of compilation\n\n" )
endif()

#check for EIGEN and set parameters if used
message("\n\n Search for EIGEN")
find_package (Eigen3 3.3 NO_MODULE)
if((USE_EIGEN OR NOT DEFINED USE_EIGEN) AND Eigen3_FOUND)
    message("FOUND Eigen library and compiling with it.\n\n" )
    add_compile_definitions(CPP_EIGEN)
    set(USE_EIGEN TRUE)
elseif(USE_EIGEN AND NOT Eigen3_FOUND)
    message( FATAL_ERROR "Enforcing to use EIGEN, but library can not be found.\n\n" )
else()
    message( "Skipping Eigen-part of compilation\n\n" )
endif()

#check for MKL
message("\n\n CHECK If MKL is defined using environment MKLROOT")
if((USE_MKL OR NOT DEFINED USE_MKL) AND DEFINED ENV{MKLROOT})
    message("FOUND MKL library and compiling with it.\n\n" )
    add_compile_definitions(CPP_MKL)
    include_directories( $ENV{MKLROOT}/include )
    link_directories( $ENV{MKLROOT}/lib/intel64 )
    if(NOT DEFINED MKL_linker)
        set(MKL_linker "-Wl,--no-as-needed -lmkl_gf_lp64 -lmkl_gnu_thread -lmkl_core -lgomp -lpthread -lm -ldl") 
    endif()
    set(add_lib ${add_lib} ${MKL_linker})
    set(USE_MKL TRUE)
elseif(USE_MKL AND NOT DEFINED ENV{MKLROOT})
    message( FATAL_ERROR "Enforcing to use MKL, but library can not be found.\n\n" )
else()
    message( "Skipping MKL-part of compilation\n\n" )
endif()


#check for BLAS
message("\n\n Search for BLAS")
find_package(BLAS)
if((USE_BLAS OR NOT DEFINED USE_BLAS) AND BLAS_FOUND)
    if(USE_MKL)
        message("FOUND BLAS library, but since MKL is already found that is used.\n\n" )
        set(USE_BLAS FALSE)
    else()
        message("\n\nFOUND BLAS library and using that implementation\n\n" )
        set(USE_BLAS TRUE)
    endif()
    add_compile_definitions(CPP_BLAS)
elseif(USE_BLAS AND NOT BLAS_FOUND AND NOT USE_MKL)
    message( FATAL_ERROR "Enforcing to use BLAS, but library can not be found.\n\n" )
else()
    message( "Skipping BLAS-part of compilation\n\n" )
endif()


#check for lapack
message("\n\n Search for LAPACK")
find_package(LAPACK)
if((USE_LAPACK OR NOT DEFINED USE_LAPACK) AND LAPACK_FOUND)
    if(USE_MKL)
        message("FOUND LAPACK library, but since MKL is already found that is used.\n\n" )
        set(USE_LAPACK FALSE)
    else()
        message("FOUND LAPACK library and using that implementation\n\n" )
        set(USE_LAPACK TRUE)
    endif()
    add_compile_definitions(CPP_LAPACK)
elseif(USE_LAPACK AND NOT LAPACK_FOUND AND NOT USE_MKL)
    message( FATAL_ERROR "Enforcing to use LAPACK, but library can not be found.\n\n" )
else()
    message( "Skipping LAPACK-part of compilation\n\n" )
endif()
